<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Medicine_stock;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class medicine_stockSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Medicine_stock::create([
            'Med_No'=>'M001',
            'Med_Name'=>'Metformin',
            'Dosage'=>'500mg',
            'Consumption_time'=>'tds',
            'Unit_Price'=>'300.00',
            'Exp_Date'=>'2021-01-24',
            'Manu_Date'=>'2020-05-12',
            'Quantity'=>'10',
          ]);

          Medicine_stock::create([
            'Med_No'=>'M002',
            'Med_Name'=>'Dianil',
            'Dosage'=>'5mg',
            'Consumption_time'=>'bd',
            'Unit_Price'=>'200.00',
            'Exp_Date'=>'2021-02-24',
            'Manu_Date'=>'2020-05-12',
            'Quantity'=>'50',
          ]);
          Medicine_stock::create([
            'Med_No'=>'M003',
            'Med_Name'=>'Carbamatepine',
            'Dosage'=>'10mg',
            'Consumption_time'=>'bd',
            'Unit_Price'=>'100.00',
            'Exp_Date'=>'2021-02-14',
            'Manu_Date'=>'2020-05-22',
            'Quantity'=>'100',
          ]);
          Medicine_stock::create([
            'Med_No'=>'M004',
            'Med_Name'=>'Clobzam',
            'Dosage'=>'5mg',
            'Consumption_time'=>'bd',
            'Unit_Price'=>'500.00',
            'Exp_Date'=>'2021-03-14',
            'Manu_Date'=>'2020-05-02',
            'Quantity'=>'100',
          ]);
          Medicine_stock::create([
            'Med_No'=>'M005',
            'Med_Name'=>'Clonatepum',
            'Dosage'=>'0.5mg',
            'Consumption_time'=>'tds',
            'Unit_Price'=>'50.00',
            'Exp_Date'=>'2021-04-14',
            'Manu_Date'=>'2020-05-21',
            'Quantity'=>'100',
          ]);
          Medicine_stock::create([
            'Med_No'=>'M006',
            'Med_Name'=>'Gabapentic-Neuroutin',
            'Dosage'=>'300mg',
            'Consumption_time'=>'bd',
            'Unit_Price'=>'500.00',
            'Exp_Date'=>'2021-06-14',
            'Manu_Date'=>'2020-04-21',
            'Quantity'=>'200',
          ]);
          Medicine_stock::create([
            'Med_No'=>'M007',
            'Med_Name'=>'Diatepam',
            'Dosage'=>'5mg',
            'Consumption_time'=>'bd',
            'Unit_Price'=>'100.00',
            'Exp_Date'=>'2021-06-14',
            'Manu_Date'=>'2020-04-21',
            'Quantity'=>'100',
          ]);
          Medicine_stock::create([
            'Med_No'=>'M008',
            'Med_Name'=>'Flucxetine',
            'Dosage'=>'20mg',
            'Consumption_time'=>'bd',
            'Unit_Price'=>'150.00',
            'Exp_Date'=>'2021-07-14',
            'Manu_Date'=>'2020-02-21',
            'Quantity'=>'150',
          ]);
          Medicine_stock::create([
            'Med_No'=>'M009',
            'Med_Name'=>'Fluvoxamine',
            'Dosage'=>'50mg',
            'Consumption_time'=>'bd',
            'Unit_Price'=>'200.00',
            'Exp_Date'=>'2021-03-14',
            'Manu_Date'=>'2020-02-21',
            'Quantity'=>'150',
          ]);
          Medicine_stock::create([
            'Med_No'=>'M010',
            'Med_Name'=>'Cetiritine',
            'Dosage'=>'10mg',
            'Consumption_time'=>'bd',
            'Unit_Price'=>'200.00',
            'Exp_Date'=>'2021-03-01',
            'Manu_Date'=>'2020-02-12',
            'Quantity'=>'150',
          ]);
          Medicine_stock::create([
            'Med_No'=>'M011',
            'Med_Name'=>'Chlorpheniramine',
            'Dosage'=>'4mg',
            'Consumption_time'=>'bd',
            'Unit_Price'=>'150.00',
            'Exp_Date'=>'2021-07-01',
            'Manu_Date'=>'2020-06-12',
            'Quantity'=>'150',
          ]);
          Medicine_stock::create([
            'Med_No'=>'M012',
            'Med_Name'=>'Chlorpheniramine',
            'Dosage'=>'4mg',
            'Consumption_time'=>'bd',
            'Unit_Price'=>'150.00',
            'Exp_Date'=>'2021-07-01',
            'Manu_Date'=>'2020-06-12',
            'Quantity'=>'100',
          ]);
          Medicine_stock::create([
            'Med_No'=>'M013',
            'Med_Name'=>'Chlordiazepoxide',
            'Dosage'=>'10mg',
            'Consumption_time'=>'tds',
            'Unit_Price'=>'200.00',
            'Exp_Date'=>'2021-08-01',
            'Manu_Date'=>'2020-11-12',
            'Quantity'=>'150',

          ]);
          Medicine_stock::create([
            'Med_No'=>'M014',
            'Med_Name'=>'Diazopam',
            'Dosage'=>'5mg',
            'Consumption_time'=>'bd',
            'Unit_Price'=>'100.00',
            'Exp_Date'=>'2021-08-20',
            'Manu_Date'=>'2020-11-23',
            'Quantity'=>'200',
          ]);
          Medicine_stock::create([
            'Med_No'=>'M015',
            'Med_Name'=>'Larazepam',
            'Dosage'=>'1mg',
            'Consumption_time'=>'tds',
            'Unit_Price'=>'200.00',
            'Exp_Date'=>'2021-05-20',
            'Manu_Date'=>'2020-04-23',
            'Quantity'=>'200',
          ]);
    }
}
